// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// unNormedMargLogLikeCpp
double unNormedMargLogLikeCpp(double phi, double shift, int z11, int z12, int z21, int z22, int m011, int m012, int m021, int m022, int y01, int y02, int N1, int N2, int N01, int N02);
RcppExport SEXP poisDoubleSamp_unNormedMargLogLikeCpp(SEXP phiSEXP, SEXP shiftSEXP, SEXP z11SEXP, SEXP z12SEXP, SEXP z21SEXP, SEXP z22SEXP, SEXP m011SEXP, SEXP m012SEXP, SEXP m021SEXP, SEXP m022SEXP, SEXP y01SEXP, SEXP y02SEXP, SEXP N1SEXP, SEXP N2SEXP, SEXP N01SEXP, SEXP N02SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< double >::type phi(phiSEXP );
        Rcpp::traits::input_parameter< double >::type shift(shiftSEXP );
        Rcpp::traits::input_parameter< int >::type z11(z11SEXP );
        Rcpp::traits::input_parameter< int >::type z12(z12SEXP );
        Rcpp::traits::input_parameter< int >::type z21(z21SEXP );
        Rcpp::traits::input_parameter< int >::type z22(z22SEXP );
        Rcpp::traits::input_parameter< int >::type m011(m011SEXP );
        Rcpp::traits::input_parameter< int >::type m012(m012SEXP );
        Rcpp::traits::input_parameter< int >::type m021(m021SEXP );
        Rcpp::traits::input_parameter< int >::type m022(m022SEXP );
        Rcpp::traits::input_parameter< int >::type y01(y01SEXP );
        Rcpp::traits::input_parameter< int >::type y02(y02SEXP );
        Rcpp::traits::input_parameter< int >::type N1(N1SEXP );
        Rcpp::traits::input_parameter< int >::type N2(N2SEXP );
        Rcpp::traits::input_parameter< int >::type N01(N01SEXP );
        Rcpp::traits::input_parameter< int >::type N02(N02SEXP );
        double __result = unNormedMargLogLikeCpp(phi, shift, z11, z12, z21, z22, m011, m012, m021, m022, y01, y02, N1, N2, N01, N02);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// unNormedMargLogLikeMaxLogTermCpp
double unNormedMargLogLikeMaxLogTermCpp(double phi, int z11, int z12, int z21, int z22, int m011, int m012, int m021, int m022, int y01, int y02, int N1, int N2, int N01, int N02);
RcppExport SEXP poisDoubleSamp_unNormedMargLogLikeMaxLogTermCpp(SEXP phiSEXP, SEXP z11SEXP, SEXP z12SEXP, SEXP z21SEXP, SEXP z22SEXP, SEXP m011SEXP, SEXP m012SEXP, SEXP m021SEXP, SEXP m022SEXP, SEXP y01SEXP, SEXP y02SEXP, SEXP N1SEXP, SEXP N2SEXP, SEXP N01SEXP, SEXP N02SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< double >::type phi(phiSEXP );
        Rcpp::traits::input_parameter< int >::type z11(z11SEXP );
        Rcpp::traits::input_parameter< int >::type z12(z12SEXP );
        Rcpp::traits::input_parameter< int >::type z21(z21SEXP );
        Rcpp::traits::input_parameter< int >::type z22(z22SEXP );
        Rcpp::traits::input_parameter< int >::type m011(m011SEXP );
        Rcpp::traits::input_parameter< int >::type m012(m012SEXP );
        Rcpp::traits::input_parameter< int >::type m021(m021SEXP );
        Rcpp::traits::input_parameter< int >::type m022(m022SEXP );
        Rcpp::traits::input_parameter< int >::type y01(y01SEXP );
        Rcpp::traits::input_parameter< int >::type y02(y02SEXP );
        Rcpp::traits::input_parameter< int >::type N1(N1SEXP );
        Rcpp::traits::input_parameter< int >::type N2(N2SEXP );
        Rcpp::traits::input_parameter< int >::type N01(N01SEXP );
        Rcpp::traits::input_parameter< int >::type N02(N02SEXP );
        double __result = unNormedMargLogLikeMaxLogTermCpp(phi, z11, z12, z21, z22, m011, m012, m021, m022, y01, y02, N1, N2, N01, N02);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
